name: Publish to npm

on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: yarn install
            - run: yarn run build
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.FE_USER_NPM_TOKEN }}
